### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by tgvdufuture** [Ishaan35/Unity3D-Mario-Kart-Racing-Game#11]
Hey, I got a problem. The game works but the other players (ai) are not with the player and the turn control system does not work, how can I fix this?

**Comment by Ishaan35** [comment]
What version of Unity are you using?

**Comment by tgvdufuture** [comment]
I'm using version 2021.1.3f1 and have downloaded it from google drive.

**Comment by tgvdufuture** [comment]
I looked and in fact the other players (ai) are actually under the map but they don't follow the course.

**Comment by Ishaan35** [comment]
Which version of the game did you download? Is it the version from my
latest youtube video? Just asking as I have never heard of this specific
issue before and I myself am unsure what is happening.

**Comment by Ishaan35** [comment]
Try checking the path game objects in the scene, and see if they are
following the track. They should be different colored line segments. If you
are on the Waterpark track I haven't implemented any computer player track
movements yet. The other tracks should work fine.

**Comment by tgvdufuture** [comment]
Yes, that's the problem. How can I change scenes when I can't find the files ?

**Comment by Ishaan35** [comment]
The files are in the game 100%. Unless you downloaded  the source  code
from github directly, everything should be there. The full project is in
the google drive link under my latest YouTube video.
